document.addEventListener('DOMContentLoaded',async()=>{
const {$,esc,api,toast,bindTabs,bindLogout}=Talentix;
let user,ctx,board={etapas:[],cards:[]},card,cid,models=[],talent,pools=[],members=[],page=1,n=0;
let eid=new URLSearchParams(location.search).get('empresa');
const query=()=>eid?'?id_empresa='+encodeURIComponent(eid):'';
const send=(path,method,data)=>api(path,{method,...(data!==undefined?{body:JSON.stringify(data)}:{})});
const guard=(fn,error)=>async e=>{if(e?.type==='submit')e.preventDefault();const b=e?.submitter;if(b)b.disabled=true;if(error)$(error).textContent='';try{await fn(e);}catch(x){if(error)$(error).textContent=x.message;else toast(x.message,true);}finally{if(b)b.disabled=b.dataset.sent==='true';}};
const options=(rows,key,label,blank)=>`<option value="">${esc(blank||'Selecione')}</option>`+rows.map(r=>`<option value="${esc(r[key])}">${esc(r[label])}</option>`).join('');
const active=()=>board.etapas.filter(e=>e.Ativa),job=()=>$('#atsVaga').value;
const states={ativo:'Ativo',aprovado:'Aprovado',reprovado:'Reprovado',retirado:'Retirado',desistente:'Desistente'};
const on=(id,type,fn,error)=>$(id).addEventListener(type,guard(fn,error));
bindLogout();bindTabs(guard(async tab=>{if(tab==='talentos'){await loadPools();await search();}}));
document.querySelectorAll('[data-fechar]').forEach(b=>b.onclick=()=>$('#'+b.dataset.fechar).close());
async function init(){ctx=await api('/ats/contexto'+query());eid=ctx.empresa.ID_Empresas;$('#atsEmpresa').textContent=ctx.empresa.NomeFantasia||ctx.empresa.RazaoSocial;$('#atsVaga').innerHTML=options(ctx.vagas,'ID_Vagas','Titulo','Selecione uma vaga');$('#atsInviteVaga').innerHTML=options(ctx.vagas,'ID_Vagas','Titulo');$('#atsResponsavelFiltro').innerHTML=options(ctx.avaliadores,'ID_Usuarios','Nome','Todos');$('#atsCardResponsavel').innerHTML=options(ctx.avaliadores,'ID_Usuarios','Nome','Sem responsável');await loadPools();await search();}
async function loadBoard(initialize=true){if(!job()){board={etapas:[],cards:[]};render();return;}if(initialize)await send(`/ats/vagas/${job()}/inicializar`,'POST');const q=new URLSearchParams();if($('#atsResponsavelFiltro').value)q.set('responsavel',$('#atsResponsavelFiltro').value);if($('#atsEstadoFiltro').value)q.set('estado',$('#atsEstadoFiltro').value);board=await api(`/ats/vagas/${job()}/pipeline?${q}`);render();}
function render(){
$('#atsModeloEtapa').innerHTML=options(active(),'ID_Etapa','Nome');$('#atsAvaliarCandidato').innerHTML=options(board.cards,'ID_Candidaturas','NomeCandidato');$('#atsBoardStatus').textContent=job()?`${board.cards.length} candidatos encontrados.`:'Selecione uma vaga.';
$('#atsEtapasLista').innerHTML=board.etapas.map(e=>`<div class="list-item"><p>${esc(e.Ordem)}. ${esc(e.Nome)} ${e.Ativa?'':'(arquivada)'}</p><button class="btn btn-secondary" type="button" data-stage="${esc(e.ID_Etapa)}">Editar etapa</button></div>`).join('');
$('#atsBoard').innerHTML=board.etapas.filter(e=>e.Ativa||board.cards.some(c=>c.ID_Etapa===e.ID_Etapa)).map(e=>{const list=board.cards.filter(c=>c.ID_Etapa===e.ID_Etapa);return `<section class="card ats-column" data-column="${esc(e.ID_Etapa)}" aria-label="${esc(e.Nome)}"><h3>${esc(e.Nome)} (${list.length})</h3>${list.map(c=>`<article class="card" draggable="${c.CandidaturaAtiva?'true':'false'}" data-card="${esc(c.ID_Candidaturas)}"><h4>${esc(c.NomeCandidato)}</h4><p>${esc(states[c.Estado])} · Posição ${esc(c.Ordem)}</p><p>Entrada: ${esc(c.EntradaEm)}</p><p>Responsável: ${esc(ctx.avaliadores.find(u=>u.ID_Usuarios===c.ID_Responsavel)?.Nome||'Sem responsável')}</p><p>Prazo: ${esc(c.Prazo||'Não definido')}</p><button type="button" class="btn btn-secondary" data-move="${esc(c.ID_Candidaturas)}">Movimentar / detalhes</button></article>`).join('')||'<p>Nenhum candidato nesta etapa.</p>'}</section>`;}).join('');}
for(const id of ['#atsVaga','#atsResponsavelFiltro','#atsEstadoFiltro'])on(id,'change',()=>loadBoard());on('#atsAtualizar','click',()=>loadBoard());
$('#atsEtapaCancelar').onclick=()=>{$('#atsEtapaForm').reset();$('#atsEtapaId').value='';};
on('#atsEtapasLista','click',e=>{const b=e.target.closest('[data-stage]');if(!b)return;const t=board.etapas.find(t=>t.ID_Etapa===b.dataset.stage);$('#atsEtapaId').value=t.ID_Etapa;$('#atsEtapaNome').value=t.Nome;$('#atsEtapaOrdem').value=t.Ordem;$('#atsEtapaAtiva').checked=!!t.Ativa;$('#atsEtapaNome').focus();});
on('#atsEtapaForm','submit',async()=>{if(!job())throw Error('Selecione uma vaga.');const id=$('#atsEtapaId').value;await send(id?'/ats/etapas/'+id:`/ats/vagas/${job()}/etapas`,id?'PUT':'POST',{nome:$('#atsEtapaNome').value.trim(),ordem:+$('#atsEtapaOrdem').value,ativa:$('#atsEtapaAtiva').checked});$('#atsEtapaForm').reset();$('#atsEtapaId').value='';await loadBoard();toast('Etapa salva.');});
async function openCard(id){card=board.cards.find(c=>c.ID_Candidaturas===id);if(!card)return;$('#atsCardTitulo').textContent=card.NomeCandidato;$('#atsCardEtapa').innerHTML=options(active(),'ID_Etapa','Nome');$('#atsCardEtapa').value=card.ID_Etapa;for(const [field,key]of [['Responsavel','ID_Responsavel'],['Prazo','Prazo'],['Ordem','Ordem'],['Estado','Estado'],['Notas','Notas'],['Motivo','Motivo']])$('#atsCard'+field).value=card[key]??'';$('#atsCardSalvar').disabled=!card.CandidaturaAtiva;$('#atsCardErro').textContent='';const events=await api('/ats/candidaturas/'+id+'/historico');$('#atsHistorico').innerHTML=events.map(e=>{const d=typeof e.Depois==='string'?JSON.parse(e.Depois):e.Depois;const before=typeof e.Antes==='string'?JSON.parse(e.Antes):e.Antes;const label=id=>board.etapas.find(t=>t.ID_Etapa===id)?.Nome||id||'Entrada';return `<article class="list-item"><div><p>${esc(e.CriadoEm)} · ${esc(e.Acao)} · ${esc(e.ID_Usuarios)}</p><p>${esc(label(before?.ID_Etapa))} → ${esc(label(d?.ID_Etapa||d?.etapa))}</p><p>${esc(d?.Estado||d?.estado)} · ${esc(d?.Motivo)}</p><p>${esc(d?.Notas)}</p></div></article>`;}).join('')||'<p>Sem movimentações.</p>';$('#atsCardDialog').showModal();}
on('#atsBoard','click',async e=>{const b=e.target.closest('[data-move]');if(b)await openCard(b.dataset.move);});
on('#atsCardForm','submit',async()=>{await send('/ats/candidaturas/'+card.ID_Candidaturas+'/card','PUT',{id_etapa:$('#atsCardEtapa').value,versao:card.Versao,ordem:+$('#atsCardOrdem').value,responsavel:$('#atsCardResponsavel').value||null,prazo:$('#atsCardPrazo').value||null,estado:$('#atsCardEstado').value,notas:$('#atsCardNotas').value.trim()||null,motivo:$('#atsCardMotivo').value.trim()||null});$('#atsCardDialog').close();await loadBoard(false);toast('Movimentação registrada.');},'#atsCardErro');
let dragged;$('#atsBoard').addEventListener('dragstart',e=>{dragged=e.target.closest('[data-card]')?.dataset.card;if(dragged)e.dataTransfer.setData('text/plain',dragged);});$('#atsBoard').addEventListener('dragover',e=>{const col=e.target.closest('[data-column]');if(col){e.preventDefault();col.classList.add('ats-drop');}});const clear=()=>document.querySelectorAll('.ats-drop').forEach(e=>e.classList.remove('ats-drop'));$('#atsBoard').addEventListener('dragleave',clear);$('#atsBoard').addEventListener('dragend',()=>{clear();dragged=null;});
on('#atsBoard','drop',async e=>{e.preventDefault();clear();const dest=e.target.closest('[data-column]'),c=board.cards.find(c=>c.ID_Candidaturas===(dragged||e.dataTransfer.getData('text/plain')));if(!dest||!c||!c.CandidaturaAtiva||dest.dataset.column===c.ID_Etapa)return;await send('/ats/candidaturas/'+c.ID_Candidaturas+'/card','PUT',{id_etapa:dest.dataset.column,versao:c.Versao,ordem:board.cards.filter(x=>x.ID_Etapa===dest.dataset.column).length,responsavel:c.ID_Responsavel,prazo:c.Prazo,estado:c.Estado,notas:c.Notas,motivo:c.Motivo});await loadBoard(false);toast('Candidato movimentado.');});
function addCriterion(){if($('#atsCriterios').children.length>=30)return;const i=++n,row=document.createElement('div');row.className='ats-criteria-row';row.innerHTML=`<div class="grid-2"><div class="field"><label for="criterion-${i}">Nome do critério</label><input id="criterion-${i}" data-name required maxlength="150"></div><div class="field"><label for="weight-${i}">Peso</label><input id="weight-${i}" data-weight type="number" min="0.01" max="100" step="0.01" value="1" required></div></div><label><input data-required type="checkbox" checked> Obrigatório</label><button type="button" class="btn btn-secondary" data-remove-criterion>Remover critério</button>`;$('#atsCriterios').append(row);}
addCriterion();$('#atsAdicionarCriterio').onclick=addCriterion;$('#atsCriterios').onclick=e=>{if(e.target.closest('[data-remove-criterion]')&&$('#atsCriterios').children.length>1)e.target.closest('.ats-criteria-row').remove();};
on('#atsModeloForm','submit',async()=>{if(!$('#atsModeloEtapa').value)throw Error('Selecione uma vaga e etapa.');const criterios=[...$('#atsCriterios').children].map(r=>({nome:r.querySelector('[data-name]').value.trim(),peso:+r.querySelector('[data-weight]').value,obrigatorio:r.querySelector('[data-required]').checked}));await send('/ats/etapas/'+$('#atsModeloEtapa').value+'/scorecards','POST',{nome:$('#atsModeloNome').value.trim(),cego:$('#atsModeloCego').checked,criterios});toast('Scorecard criado. Abra um candidato para avaliar.');$('#atsModeloNome').value='';});
const evaluation=d=>d.bloqueado?'<p>As avaliações dos outros ficam ocultas até você enviar a sua.</p>':`<p>Média dos avaliadores: ${d.media==null?'Sem notas':Number(d.media).toFixed(2)+' / 5'}. A decisão é humana.</p>`+d.avaliacoes.map(a=>`<article class="card"><h4>${esc(a.Avaliador)} · ${esc(a.CriadoEm)}</h4><p>Notas: ${esc(a.Notas.map(n=>n??'Não avaliado').join(' / '))} · Média ponderada: ${Number(a.Media).toFixed(2)}</p><p>${esc(a.Comentario)}</p><p>Parecer: ${esc(a.Parecer)}</p><p>Recomendação: ${esc(a.Recomendacao)}</p></article>`).join('');
async function loadRating(){const m=models.find(m=>m.ID_Modelo===$('#atsScoreModelo').value);$('#atsScoreForm').reset();$('#atsScoreErro').textContent='';if(!m){$('#atsNotas').textContent='Crie um scorecard na aba Scorecards.';$('#atsScoreEnviar').disabled=true;$('#atsAvaliacoes').textContent='Sem scorecards.';return;}$('#atsNotas').innerHTML=m.Criterios.map((c,i)=>`<div class="field"><label for="note-${i}">${esc(c.nome)} — peso ${esc(c.peso)} ${c.obrigatorio?'(obrigatório)':'(opcional)'}</label><input id="note-${i}" data-note type="number" min="0" max="5" step="0.1" ${c.obrigatorio?'required':''}></div>`).join('');const d=await api(`/ats/candidaturas/${cid}/scorecards/${m.ID_Modelo}/avaliacoes`);$('#atsAvaliacoes').innerHTML=evaluation(d);const own=d.avaliacoes.find(a=>a.ID_Usuarios===user.id_usuario);$('#atsScoreEnviar').disabled=!!own;$('#atsScoreEnviar').dataset.sent=own?'true':'false';if(own){$('#atsScoreParecer').value=own.Parecer;$('#atsScoreComentario').value=own.Comentario||'';$('#atsScoreRecomendacao').value=own.Recomendacao;$('#atsNotas').querySelectorAll('[data-note]').forEach((e,i)=>e.value=own.Notas[i]??'');}}
async function openScore(id){cid=id;models=await api('/ats/candidaturas/'+id+'/scorecards');$('#atsScoreModelo').innerHTML=options(models,'ID_Modelo','Nome');if(models.length)$('#atsScoreModelo').value=models[0].ID_Modelo;$('#atsScoreTitulo').textContent='Avaliar '+(board.cards.find(c=>c.ID_Candidaturas===id)?.NomeCandidato||'candidato');await loadRating();$('#atsScoreDialog').showModal();}
on('#atsScoreModelo','change',loadRating,'#atsScoreErro');on('#atsAvaliarAbrir','click',async()=>{if(!$('#atsAvaliarCandidato').value)throw Error('Selecione uma vaga e candidato.');await openScore($('#atsAvaliarCandidato').value);});on('#atsCardAvaliar','click',async()=>{$('#atsCardDialog').close();await openScore(card.ID_Candidaturas);});
on('#atsScoreForm','submit',async()=>{await send(`/ats/candidaturas/${cid}/scorecards/${$('#atsScoreModelo').value}/avaliacoes`,'POST',{notas:[...$('#atsNotas').querySelectorAll('[data-note]')].map(e=>e.value===''?null:+e.value),comentario:$('#atsScoreComentario').value.trim()||null,parecer:$('#atsScoreParecer').value.trim(),recomendacao:$('#atsScoreRecomendacao').value});await loadRating();toast('Avaliação registrada.');},'#atsScoreErro');
async function loadPools(){pools=await api('/ats/pools'+query());const before=$('#atsBuscaPool').value;$('#atsBuscaPool').innerHTML=options(pools,'ID_Pool','Nome','Todos');$('#atsBuscaPool').value=before;$('#atsMemberPool').innerHTML=options(pools,'ID_Pool','Nome');$('#atsPoolsLista').innerHTML=pools.map(p=>`<div class="list-item"><p>${esc(p.Nome)}</p><div class="list-item__actions"><button type="button" class="btn btn-secondary" data-pool="${esc(p.ID_Pool)}">Renomear</button><button type="button" class="btn-danger-ghost" data-archive="${esc(p.ID_Pool)}">Arquivar pool</button></div></div>`).join('')||'<p>Crie o primeiro pool.</p>';}
$('#atsPoolNovo').onclick=()=>{$('#atsPoolForm').reset();$('#atsPoolId').value='';};on('#atsPoolForm','submit',async()=>{const id=$('#atsPoolId').value;await send(id?'/ats/pools/'+id:'/ats/pools'+query(),id?'PUT':'POST',{nome:$('#atsPoolNome').value.trim()});$('#atsPoolForm').reset();$('#atsPoolId').value='';await loadPools();toast('Pool salvo.');});on('#atsPoolsLista','click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.pool){const p=pools.find(p=>p.ID_Pool===b.dataset.pool);$('#atsPoolId').value=p.ID_Pool;$('#atsPoolNome').value=p.Nome;$('#atsPoolNome').focus();}if(b.dataset.archive&&confirm('Arquivar este pool? O histórico dos processos será preservado.')){await send('/ats/pools/'+b.dataset.archive,'DELETE');await loadPools();await search();}});
async function search(){const q=new URLSearchParams({id_empresa:eid,pagina:page});for(const [field,key]of [['Nome','nome'],['Skill','skill'],['Formacao','formacao'],['Experiencia','experiencia'],['Tag','tag']])if($('#atsBusca'+field).value.trim())q.set(key,$('#atsBusca'+field).value.trim());if($('#atsBuscaPool').value)q.set('id_pool',$('#atsBuscaPool').value);if($('#atsBuscaFavorito').checked)q.set('favorito','true');if($('#atsBuscaAvaliado').checked)q.set('avaliado','true');const d=await api('/ats/talentos?'+q);$('#atsTotal').textContent=`${d.total} talentos autorizados — página ${page}`;$('#atsAnterior').disabled=page<=1;$('#atsProxima').disabled=page*20>=d.total;$('#atsTalentos').innerHTML=d.itens.map(c=>`<article class="list-item"><div><h3>${esc(c.Nome)}</h3><p>${esc(c.TituloProfissional)} · ${esc(c.Cidade)} ${esc(c.Estado)}</p></div><button type="button" class="btn btn-secondary" data-talent="${esc(c.ID_Candidatos)}" data-name="${esc(c.Nome)}">Histórico / pools / convite</button></article>`).join('')||'<p>Nenhum talento com esses filtros e autorização.</p>';}
on('#atsBuscaForm','submit',async()=>{page=1;await search();});on('#atsAnterior','click',async()=>{page--;await search();});on('#atsProxima','click',async()=>{page++;await search();});
async function talentHistory(){const d=await api('/ats/talentos/'+talent+'/historico'+query());members=d.pools;$('#atsTalentHistorico').innerHTML=d.processos.map(c=>`<article class="card"><h3>${esc(c.Titulo)}</h3><p>${esc(c.CriadaEm)} · ${esc(states[c.Estado]||c.ID_Status_Candidatura)}</p><p>Motivo anterior: ${esc(c.Motivo||'Não informado')}</p>${c.scorecards.map(s=>`<h4>${esc(s.modelo.Nome)}</h4>${evaluation(s)}`).join('')}</article>`).join('');$('#atsTalentPools').innerHTML=members.map(m=>`<article class="list-item"><div><p>${esc(m.Nome)} ${m.Favorito?'· Favorito':''}</p><p>${esc(m.Tags.join(', '))}</p><p>${esc(m.Notas)}</p></div><div class="list-item__actions"><button type="button" class="btn btn-secondary" data-member="${esc(m.ID_Pool)}">Editar tags / notas</button><button type="button" class="btn-danger-ghost" data-remove="${esc(m.ID_Pool)}">Remover do pool</button></div></article>`).join('')||'<p>Sem pools.</p>';}
on('#atsTalentos','click',async e=>{const b=e.target.closest('[data-talent]');if(!b)return;talent=b.dataset.talent;$('#atsTalentTitulo').textContent=b.dataset.name;$('#atsTalentErro').textContent='';$('#atsMemberForm').reset();await talentHistory();$('#atsTalentDialog').showModal();});
function fillMember(){const m=members.find(m=>m.ID_Pool===$('#atsMemberPool').value);$('#atsMemberTags').value=m?.Tags.join(', ')||'';$('#atsMemberNotas').value=m?.Notas||'';$('#atsMemberFavorito').checked=!!m?.Favorito;}
$('#atsMemberPool').onchange=fillMember;on('#atsTalentPools','click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.member){$('#atsMemberPool').value=b.dataset.member;fillMember();$('#atsMemberTags').focus();}if(b.dataset.remove){await send(`/ats/pools/${b.dataset.remove}/candidatos/${talent}`,'DELETE');await talentHistory();await search();}},'#atsTalentErro');
on('#atsMemberForm','submit',async()=>{if(!$('#atsMemberPool').value)throw Error('Crie e selecione um pool.');await send(`/ats/pools/${$('#atsMemberPool').value}/candidatos/${talent}`,'PUT',{tags:$('#atsMemberTags').value.split(',').map(t=>t.trim()).filter(Boolean),favorito:$('#atsMemberFavorito').checked,notas:$('#atsMemberNotas').value.trim()||null});await talentHistory();await search();toast('Talento salvo no pool.');},'#atsTalentErro');
on('#atsInviteForm','submit',async()=>{await send('/ats/talentos/'+talent+'/convites','POST',{id_vaga:$('#atsInviteVaga').value});toast('Convite enviado nas notificações do candidato.');},'#atsTalentErro');
on('#atsAdmin','submit',async()=>{eid=$('#atsEmpresaId').value.trim();const url=new URL(location);url.searchParams.set('empresa',eid);history.replaceState(null,'',url);await init();},'#atsErro');
try{user=await api('/auth/me');if(!['empresa','recrutador','administrador'].includes(user.tipo_usuario))throw Error('ATS restrito à empresa, recrutador ou administrador autorizado.');$('#atsVoltar').href=user.tipo_usuario==='administrador'?'dashboard-admin.html':user.tipo_usuario==='recrutador'?'dashboard-recrutador.html':'dashboard-empresa.html';if(user.tipo_usuario==='administrador'){$('#atsAdmin').hidden=false;if(!eid){$('#atsEmpresa').textContent='Selecione uma empresa para administrar.';return;}$('#atsEmpresaId').value=eid;}await init();}catch(e){$('#atsErro').textContent=e.message;$('#atsEmpresa').textContent='Não foi possível abrir o ATS.';}
});
