/* ATS on a real FastAPI/MySQL instance, via browser forms and keyboard. */
const assert=require('node:assert/strict');const {chromium}=require('playwright');const {audit}=require('./axe.cjs');
if(process.env.TALENTIX_ISOLATED_TESTS!=='1')throw Error('Somente ambiente MySQL descartável.');
const API=process.env.TEST_API_URL||'http://127.0.0.1:8000',FRONT=process.env.TEST_FRONTEND_URL||'http://127.0.0.1:5500';
process.env.A11Y_REPORT='ats-real';
(async()=>{const browser=await chromium.launch({executablePath:process.env.TEST_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox']});const contexts=[];try{
 const nonce=Date.now();
 async function account(role){const ctx=await browser.newContext();contexts.push(ctx);const email=`${role}-${contexts.length}-${nonce}@ats-browser.example.com`,d={nome:'ATS '+role,email,senha:'Dezembro123!'};if(role==='empresa'){d.razao_social='Empresa ATS navegador';d.cnpj=String(nonce+contexts.length).padStart(14,'0');}let r=await ctx.request.post(API+'/auth/cadastro/'+role,{data:d});assert.equal(r.status(),201,await r.text());const ids=await r.json();r=await ctx.request.post(API+'/auth/login',{data:{email,senha:d.senha}});assert.ok(r.ok(),await r.text());return {ctx,ids,page:await ctx.newPage()};}
 async function request(a,method,path,data,status=200){const cookies=await a.ctx.cookies(API);const csrf=cookies.find(c=>c.name==='talentix_csrf')?.value;const r=await a.ctx.request.fetch(API+path,{method,data,headers:{'X-CSRF-Token':csrf||''}});assert.equal(r.status(),status,await r.text());return r.json();}
 async function submit(p,sel,route,method='POST'){const [r]=await Promise.all([p.waitForResponse(r=>r.url().includes(route)&&r.request().method()===method),p.locator(sel).click()]);assert.ok(r.ok(),await r.text());return r.json();}
 const e=await account('empresa'),c=await account('candidato');
 const v=await request(e,'POST','/vagas',{id_empresa:e.ids.id_empresa,titulo:'ATS navegador '+nonce,descricao:'Python e SQL',modalidade:'Remoto',nivel:'Junior'},201);await request(e,'PATCH',`/vagas/${v.ID_Vagas}/publicar`);
 const ca=await request(c,'POST','/candidaturas',{id_vaga:v.ID_Vagas},201);
 await c.page.goto(FRONT+'/html/dashboard-candidato.html');await c.page.locator('#atsConsentLista [data-consent]').waitFor();await submit(c.page,'#atsConsentLista [data-consent]','/ats/consentimentos/','PUT');
 const p=e.page;await p.goto(FRONT+'/html/dashboard-empresa.html');await p.locator('a[href="ats.html"]').click();await p.waitForURL('**/ats.html');await p.locator('#atsEmpresa').filter({hasText:'Empresa ATS navegador'}).waitFor();await p.locator('#atsVaga').selectOption(v.ID_Vagas);await p.locator(`[data-move="${ca.ID_Candidaturas}"]`).waitFor();
 await p.locator(`[data-move="${ca.ID_Candidaturas}"]`).focus();await p.keyboard.press('Enter');const second=await p.locator('#atsCardEtapa option').nth(2).getAttribute('value');await p.locator('#atsCardEtapa').selectOption(second);await p.locator('#atsCardResponsavel').selectOption(e.ids.id_usuario);await p.locator('#atsCardPrazo').fill('2026-12-20');await p.locator('#atsCardNotas').fill('Somente RH');await submit(p,'#atsCardSalvar','/card','PUT');await p.locator('#atsCardDialog').waitFor({state:'hidden'});
 await p.locator('.nav-item[data-tab="scorecards"]').click();await p.locator('#atsModeloEtapa').selectOption(second);await p.locator('#atsModeloNome').fill('Entrevista técnica');await p.locator('#atsCriterios [data-name]').fill('Python');await submit(p,'#atsModeloForm button[type="submit"]','/scorecards');await p.locator('#atsAvaliarCandidato').selectOption(ca.ID_Candidaturas);await p.locator('#atsAvaliarAbrir').click();await p.locator('#atsScoreDialog[open]').waitFor();await p.locator('#note-0').fill('4');await p.locator('#atsScoreParecer').fill('Boa base, revisar SQL');await submit(p,'#atsScoreEnviar','/avaliacoes');await p.locator('#atsAvaliacoes').filter({hasText:'4.00'}).waitFor();await p.keyboard.press('Escape');
 await p.locator('.nav-item[data-tab="talentos"]').click();await p.locator('#tab-talentos details summary').click();await p.locator('#atsPoolNome').fill('Backend');await submit(p,'#atsPoolForm button[type="submit"]','/ats/pools');await p.locator(`[data-talent="${c.ids.id_candidato}"]`).click();await p.locator('#atsTalentDialog[open]').waitFor();const pid=await p.locator('#atsMemberPool option').nth(1).getAttribute('value');await p.locator('#atsMemberPool').selectOption(pid);await p.locator('#atsMemberTags').fill('Python, Backend');await p.locator('#atsMemberFavorito').check();await p.locator('#atsMemberNotas').fill('Talento de destaque');await submit(p,'#atsMemberForm button','/candidatos/','PUT');await p.locator('#atsTalentPools').filter({hasText:'Talento de destaque'}).waitFor();await p.locator('#atsInviteVaga').selectOption(v.ID_Vagas);await submit(p,'#atsInviteForm button','/convites');await p.keyboard.press('Escape');
 for(const width of [390,768,1440]){await p.setViewportSize({width,height:900});for(const tab of ['pipeline','scorecards','talentos']){await p.locator(`.nav-item[data-tab="${tab}"]`).click();await p.waitForLoadState('networkidle');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await audit(p,'ats-real-'+tab+'-'+width);}}
 const candidateData=await request(c,'GET','/candidaturas/'+ca.ID_Candidaturas);assert.equal(candidateData.ID_Status_Candidatura,2);assert.ok(!JSON.stringify(candidateData).includes('Somente RH'));
 await request(c,'PUT','/ats/consentimentos/'+e.ids.id_empresa,{autorizado:false});assert.equal((await request(e,'GET','/ats/talentos')).total,0);
 console.log('Real MySQL ATS E2E: consent, pipeline, keyboard move, scorecard, pools, invitation and revocation passed.');
}finally{for(const c of contexts)await c.close();await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
