CREATE TABLE IF NOT EXISTS Contatos (
    ID_Contatos CHAR(36) NOT NULL PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    Email VARCHAR(150) NOT NULL,
    Assunto VARCHAR(100) NOT NULL,
    Mensagem TEXT NOT NULL,
    Lido BOOLEAN NOT NULL DEFAULT FALSE,
    CriadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
