-- ATS: novas tabelas; registros e histórico existentes preservados.
CREATE TABLE IF NOT EXISTS ATS_Etapas (
ID_Etapa CHAR(36) PRIMARY KEY, ID_Vagas CHAR(36) NOT NULL, Nome VARCHAR(150) NOT NULL,
Ordem INT NOT NULL, Ativa BOOLEAN NOT NULL DEFAULT 1, KEY IX_ATS_Etapas_Vaga(ID_Vagas,Ativa,Ordem),
FOREIGN KEY(ID_Vagas) REFERENCES Vagas(ID_Vagas)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ATS_Cards (
ID_Candidaturas CHAR(36) PRIMARY KEY, ID_Etapa CHAR(36) NOT NULL,
ID_Responsavel CHAR(36) NULL, Prazo DATE NULL, EntradaEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
Ordem INT NOT NULL DEFAULT 0, Estado VARCHAR(20) NOT NULL DEFAULT 'ativo', Notas TEXT NULL, Motivo TEXT NULL,
Versao INT NOT NULL DEFAULT 1, KEY IX_ATS_Cards_Etapa(ID_Etapa,Estado,Ordem),
FOREIGN KEY(ID_Candidaturas) REFERENCES Candidaturas(ID_Candidaturas),
FOREIGN KEY(ID_Etapa) REFERENCES ATS_Etapas(ID_Etapa), FOREIGN KEY(ID_Responsavel) REFERENCES Usuarios(ID_Usuarios)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ATS_Eventos (
ID_Evento CHAR(36) PRIMARY KEY, ID_Candidaturas CHAR(36) NOT NULL, ID_Usuarios CHAR(36) NOT NULL,
Acao VARCHAR(50) NOT NULL, Sequencia INT NOT NULL, Antes JSON NULL, Depois JSON NULL, CriadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
UNIQUE KEY UQ_ATS_Eventos_Sequencia(ID_Candidaturas,Sequencia), FOREIGN KEY(ID_Candidaturas) REFERENCES Candidaturas(ID_Candidaturas),
FOREIGN KEY(ID_Usuarios) REFERENCES Usuarios(ID_Usuarios)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ATS_Modelos (
ID_Modelo CHAR(36) PRIMARY KEY, ID_Etapa CHAR(36) NOT NULL, Nome VARCHAR(150) NOT NULL,
Cego BOOLEAN NOT NULL DEFAULT 1, Criterios JSON NOT NULL, CriadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
KEY IX_ATS_Modelos_Etapa(ID_Etapa), FOREIGN KEY(ID_Etapa) REFERENCES ATS_Etapas(ID_Etapa)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ATS_Avaliacoes (
ID_Avaliacao CHAR(36) PRIMARY KEY, ID_Modelo CHAR(36) NOT NULL,
ID_Candidaturas CHAR(36) NOT NULL, ID_Usuarios CHAR(36) NOT NULL, Notas JSON NOT NULL,
Comentario TEXT NULL, Parecer TEXT NOT NULL, Recomendacao VARCHAR(20) NOT NULL, Media DECIMAL(8,4) NULL,
CriadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY UQ_ATS_Avaliacao(ID_Modelo,ID_Candidaturas,ID_Usuarios),
KEY IX_ATS_Avaliacoes_Candidato(ID_Candidaturas,CriadoEm), FOREIGN KEY(ID_Modelo) REFERENCES ATS_Modelos(ID_Modelo),
FOREIGN KEY(ID_Candidaturas) REFERENCES Candidaturas(ID_Candidaturas), FOREIGN KEY(ID_Usuarios) REFERENCES Usuarios(ID_Usuarios)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ATS_Consentimentos (
ID_Candidatos CHAR(36) NOT NULL, ID_Empresas CHAR(36) NOT NULL, Autorizado BOOLEAN NOT NULL,
AtualizadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(ID_Candidatos,ID_Empresas),
FOREIGN KEY(ID_Candidatos) REFERENCES Candidatos(ID_Candidatos), FOREIGN KEY(ID_Empresas) REFERENCES Empresas(ID_Empresas)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ATS_Pools (
ID_Pool CHAR(36) PRIMARY KEY, ID_Empresas CHAR(36) NOT NULL, Nome VARCHAR(150) NOT NULL,
Ativo BOOLEAN NOT NULL DEFAULT 1, KEY IX_ATS_Pools_Empresa(ID_Empresas,Ativo),
FOREIGN KEY(ID_Empresas) REFERENCES Empresas(ID_Empresas)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ATS_Membros (
ID_Pool CHAR(36) NOT NULL, ID_Candidatos CHAR(36) NOT NULL, Tags JSON NOT NULL,
Favorito BOOLEAN NOT NULL DEFAULT 0, Notas TEXT NULL, Ativo BOOLEAN NOT NULL DEFAULT 1,
CriadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(ID_Pool,ID_Candidatos),
KEY IX_ATS_Membros_Candidato(ID_Candidatos,Ativo), FOREIGN KEY(ID_Pool) REFERENCES ATS_Pools(ID_Pool),
FOREIGN KEY(ID_Candidatos) REFERENCES Candidatos(ID_Candidatos)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ATS_Convites (
ID_Convite CHAR(36) PRIMARY KEY, ID_Candidatos CHAR(36) NOT NULL, ID_Vagas CHAR(36) NOT NULL,
ID_Usuarios CHAR(36) NOT NULL, CriadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
UNIQUE KEY UQ_ATS_Convite(ID_Candidatos,ID_Vagas), FOREIGN KEY(ID_Candidatos) REFERENCES Candidatos(ID_Candidatos),
FOREIGN KEY(ID_Vagas) REFERENCES Vagas(ID_Vagas), FOREIGN KEY(ID_Usuarios) REFERENCES Usuarios(ID_Usuarios)
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
